add username check

diff --git a/.github/workflows/image-sync.yml b/.github/workflows/image-sync.yml
--- a/.github/workflows/image-sync.yml
+++ b/.github/workflows/image-sync.yml
@@ -30,6 +30,24 @@ jobs:
         DEST_USERNAME: ${{ secrets.ACR_USERNAME }}
         DEST_PASSWORD: ${{ secrets.ACR_PASSWORD }}
       run: |
+        # 目标注册表的用户名和密码
+        DEST_USERNAME=${DEST_USERNAME}
+        DEST_PASSWORD=${DEST_PASSWORD}
+
+        # 调试信息
+        echo "DEST_USERNAME: $DEST_USERNAME"
+        echo "DEST_PASSWORD: $DEST_PASSWORD"
+
+        # 检查用户名和密码是否为空
+        if [ -z "$DEST_USERNAME" ]; then
+          echo "Error: DEST_USERNAME is empty"
+          exit 1
+        fi
+
+        if [ -z "$DEST_PASSWORD" ]; then
+          echo "Error: DEST_PASSWORD is empty"
+          exit 1
+        fi
         IMAGES=(
           "docker.io/library/aultwarden/server:alpine registry.cn-hangzhou.aliyuncs.com/miaou/vaultwarden:alpine"
         )
